version: '3.8'
services:
  backend:
    build: ./springboot-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventorymanagement
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password


  frontend:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    image: nginx:latest
    volumes:
      - ./react-frontend/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: inventorymanagement
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"